### ISSUE TITLE
Add Wikipedia Links to Each Ocean

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/theEarthObject#1]
example:

```
arctic: {
  "wikipedia_link": "http://wiki.com/whatever"
}
```

**Comment by ChristineJ82** [comment]
Hello @iarobinson I can work on this. You can assign this to me. Thanks!

**Comment by pret3nti0u5** [comment]
Opened PR #9. Let me know if any further edits are needed.

**Comment by iarobinson** [comment]
You rock. Thanks. This issue has been addressed
