### ISSUE TITLE
Add a CSS framework

### ISSUE THREAD

**Issue by jnoc** [iarobinson/theEarthObject#10]
May I add a CSS framework that will:
- Add accessibility for light and dark mode
- Give a clean and snazzy look to the webpage

I can also add syntax highlights for the json object within its `<pre>` tag.

Cheers,
Jono

**Comment by jnoc** [comment]
The framework I would implement into this would be https://github.com/xz/new.css

**Comment by iarobinson** [comment]
@jnoc  - Do it! You rock. We currently have bootstrap as a CDN so I'm not sure how they will play together.

**Comment by iarobinson** [comment]
Actually, the more I think about this it seems like it would be better to stick with Bootstrap. The goal of this is to make a fun object that has the whole of Earth's knowledge in it. I think adding a sophisticated CSS would be a distraction from the cleanliness of the code....

That said, I'm open to it. If you make a cool PR that works well and makes the object easier to view, that would be a big win.

**Comment by jnoc** [comment]
Just making a pull, personally this is much easier to read on the eyes

```
  <body>
    <img class="logo" src="./assets/earthObject.png"/>
    <blockquote>
      <h1>The Earth Object.</h1> 
      <p>Everything on earth could be contained in a single JSON object:</p>
    </blockquote>
    <pre id="theEarthObjectsDisplay"></pre>
    <blockquote>
      <p>If you would like to add to this amazing object please click here!</p>
      <!-- :last-child on blockquote so added single style to button-->
      <a href="https://github.com/iarobinson/theEarthObject"><button style="padding-bottom: 6px;">Contribute</button></a>
    </blockquote>
</body>
```

**Comment by iarobinson** [comment]
Nice work Jnoc!

I'll be closing his for now. Please reopen if we need to discuss further.
