### ISSUE TITLE
Add Wikipedia Links to Each Continent

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/theEarthObject#2]
example:

```
"africa": {
  "wikipedia_link": "http://wiki.com/whatever"
}
```

**Comment by ChristineJ82** [comment]
Hello @iarobinson I can work on this. You can assign this to me. Thanks!

**Comment by iarobinson** [comment]
@ChristineJ82  Sorry this issue has already been addressed. But please check the issues for something new to work on. You rock!

**Comment by FionaFR** [comment]
Can you please add #hacktoberfest-accepted for this issue?
